name: thicket
description: An experimental persistent world model for LLM-based software engineering agents
version: 0.1.0

environment:
  sdk: ^3.12.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
