name: thicket_interface
description: The interface layer for Thicket, including MCP server and tools.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.12.2

dependencies:
  path: ^1.9.0
  thicket:
    path: ../world_model

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
